[project]
name = "repl-nix-dynamicdashboard"
version = "0.1.0"
description = "Dynamic Dashboard Application"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "requests>=2.32.3",
    "icalendar",
    "pytz>=2024.2",
    "gevent>=23.9.1"
]
